[package]
name = "lotus"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lotus"
path = "src/bin/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua = "0.19.4"
rayon = "1.5"
reqwest = { version = "0.11", features = ["json","blocking"] }
console = "0.15.1"
fancy-regex = "0.10.0"
tealr = { version = "0.9.0-alpha1", features=["rlua"] }
scraper = "0.13.0"
log = "0.4.17"
structopt = "0.3"
glob = "0.3.0"
indicatif = "0.17.0"
fern = "0.6.1"
chrono = "0.4.22"
serde_json = "1.0.85"
serde = { version = "1.0.144", features = ["derive"] }

[profile.release]
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
strip = true

