[package]
name = "lottas"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lottas"
path = "src/bin/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.2.2"
rlua = "0.19.4"
rayon = "1.5"
reqwest = { version = "0.11", features = ["json","blocking"] }
clap = "3.2.17"
console = "0.15.1"
fancy-regex = "0.10.0"
tealr = { version = "0.9.0-alpha1", features=["rlua"] }
scraper = "0.13.0"
log = "0.4.17"
env_logger = "0.9.0"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
structopt = "0.3"
glob = "0.3.0"



[profile.release]
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
strip = true

