name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Set the release name to the version from Cargo.toml
          name: v${{ env.CARGO_PKG_VERSION }}

  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - run: rustup target add x86_64-unknown-linux-musl
      - run: rustup target add x86_64-pc-windows-gnu
      - uses: actions-rs/cargo@v1
        with:
          command: build --release --all-features
          args: --target x86_64-unknown-linux-musl
      - uses: actions/upload-artifact@v2
        with:
          name: lotus-luajit.tar.gz
          path: target/x86_64-unknown-linux-musl/release/lotus
      - uses: actions-rs/cargo@v1
        with:
          command: build --release --features lua53
          args: --target x86_64-pc-windows-gnu
      - uses: actions/upload-artifact@v2
        with:
          name: lotus-lua53.zip
          path: target/x86_64-pc-windows-gnu/release/lotus.exe
      - uses: actions-rs/cargo@v1
        with:
          command: build --release --features lua54
      - uses: actions/upload-artifact@v2
        with:
          name: lotus-lua54.tar.gz
          path: target/release/lotus
      - uses: actions-rs/cargo@v1
        with:
          command: build --release --features vendored
      - uses: actions/upload-artifact@v2
        with:
          name: lotus-vendored.tar.gz
          path: target/release/lotus
